import deepseekConfig from './deepseek.ts';
import glmConfig from './glm.ts';
import kimiConfig from './kimi.ts';
import minimaxConfig from './minimax.ts';
import mimoConfig from './mimo.ts';
import perplexityConfig from './perplexity.ts';
import qwenConfig from './qwen.ts';
import qwenAiConfig from './qwen-ai.ts';
import zaiConfig from './zai.ts';
import stepfunConfig from './stepfun.ts';
import type { BuiltinProviderConfig } from '../../store/types.ts';
export declare const builtinProviders: BuiltinProviderConfig[];
export declare const builtinProviderMap: Record<string, BuiltinProviderConfig>;
export declare function getBuiltinProvider(id: string): BuiltinProviderConfig | undefined;
export declare function getBuiltinProviders(): BuiltinProviderConfig[];
export { deepseekConfig, glmConfig, kimiConfig, minimaxConfig, mimoConfig, perplexityConfig, qwenConfig, qwenAiConfig, zaiConfig, stepfunConfig, };
export default builtinProviders;
