export const IpcChannels = {
  PROXY_START: 'proxy:start',
  PROXY_STOP: 'proxy:stop',
  PROXY_GET_STATUS: 'proxy:getStatus',
  PROXY_STATUS_CHANGED: 'proxy:statusChanged',
  PROXY_GET_STATISTICS: 'proxy:getStatistics',
  PROXY_RESET_STATISTICS: 'proxy:resetStatistics',

  CONFIG_GET: 'config:get',
  CONFIG_UPDATE: 'config:update',
  CONFIG_CHANGED: 'config:changed',

  STORE_GET: 'store:get',
  STORE_SET: 'store:set',
  STORE_DELETE: 'store:delete',
  STORE_CLEAR_ALL: 'store:clearAll',
  STORE_INIT_ERROR: 'store:initError',
  STORE_RETRY_INIT: 'store:retryInit',

  PROVIDERS_GET_ALL: 'providers:getAll',
  PROVIDERS_GET_BUILTIN: 'providers:getBuiltin',
  PROVIDERS_ADD: 'providers:add',
  PROVIDERS_UPDATE: 'providers:update',
  PROVIDERS_DELETE: 'providers:delete',
  PROVIDERS_CHECK_STATUS: 'providers:checkStatus',
  PROVIDERS_CHECK_ALL_STATUS: 'providers:checkAllStatus',
  PROVIDERS_DUPLICATE: 'providers:duplicate',
  PROVIDERS_EXPORT: 'providers:export',
  PROVIDERS_IMPORT: 'providers:import',
  PROVIDERS_SYNC_MODELS: 'providers:syncModels',
  PROVIDERS_UPDATE_MODELS: 'providers:updateModels',
  PROVIDERS_GET_EFFECTIVE_MODELS: 'providers:getEffectiveModels',
  PROVIDERS_ADD_CUSTOM_MODEL: 'providers:addCustomModel',
  PROVIDERS_REMOVE_MODEL: 'providers:removeModel',
  PROVIDERS_RESET_MODELS: 'providers:resetModels',

  ACCOUNTS_GET_ALL: 'accounts:getAll',
  ACCOUNTS_GET_BY_ID: 'accounts:getById',
  ACCOUNTS_GET_BY_PROVIDER: 'accounts:getByProvider',
  ACCOUNTS_ADD: 'accounts:add',
  ACCOUNTS_UPDATE: 'accounts:update',
  ACCOUNTS_DELETE: 'accounts:delete',
  ACCOUNTS_VALIDATE: 'accounts:validate',
  ACCOUNTS_VALIDATE_TOKEN: 'accounts:validateToken',
  ACCOUNTS_GET_CREDITS: 'accounts:getCredits',
  ACCOUNTS_CLEAR_CHATS: 'accounts:clearChats',
  ACCOUNTS_RESET_STATUS: 'accounts:resetStatus',

  OAUTH_START_LOGIN: 'oauth:startLogin',
  OAUTH_CANCEL_LOGIN: 'oauth:cancelLogin',
  OAUTH_CALLBACK: 'oauth:callback',
  OAUTH_LOGIN_WITH_TOKEN: 'oauth:loginWithToken',
  OAUTH_VALIDATE_TOKEN: 'oauth:validateToken',
  OAUTH_REFRESH_TOKEN: 'oauth:refreshToken',
  OAUTH_GET_STATUS: 'oauth:getStatus',
  OAUTH_PROGRESS: 'oauth:progress',
  OAUTH_START_IN_APP_LOGIN: 'oauth:startInAppLogin',
  OAUTH_CANCEL_IN_APP_LOGIN: 'oauth:cancelInAppLogin',
  OAUTH_IN_APP_LOGIN_STATUS: 'oauth:inAppLoginStatus',

  LOGS_GET: 'logs:get',
  LOGS_GET_STATS: 'logs:getStats',
  LOGS_GET_TREND: 'logs:getTrend',
  LOGS_GET_ACCOUNT_TREND: 'logs:getAccountTrend',
  LOGS_CLEAR: 'logs:clear',
  LOGS_EXPORT: 'logs:export',
  LOGS_GET_BY_ID: 'logs:getById',
  LOGS_NEW_LOG: 'logs:newLog',

  REQUEST_LOGS_GET: 'requestLogs:get',
  REQUEST_LOGS_GET_BY_ID: 'requestLogs:getById',
  REQUEST_LOGS_GET_STATS: 'requestLogs:getStats',
  REQUEST_LOGS_GET_TREND: 'requestLogs:getTrend',
  REQUEST_LOGS_CLEAR: 'requestLogs:clear',
  REQUEST_LOGS_NEW: 'requestLogs:new',

  STATISTICS_GET: 'statistics:get',
  STATISTICS_GET_TODAY: 'statistics:getToday',

  APP_GET_VERSION: 'app:getVersion',
  APP_CHECK_UPDATE: 'app:checkUpdate',
  APP_DOWNLOAD_UPDATE: 'app:downloadUpdate',
  APP_INSTALL_UPDATE: 'app:installUpdate',
  APP_UPDATE_CHECKING: 'app:updateChecking',
  APP_UPDATE_AVAILABLE: 'app:updateAvailable',
  APP_UPDATE_NOT_AVAILABLE: 'app:updateNotAvailable',
  APP_UPDATE_PROGRESS: 'app:updateProgress',
  APP_UPDATE_DOWNLOADED: 'app:updateDownloaded',
  APP_UPDATE_ERROR: 'app:updateError',
  APP_GET_UPDATE_STATUS: 'app:getUpdateStatus',
  APP_MINIMIZE: 'app:minimize',
  APP_MAXIMIZE: 'app:maximize',
  APP_CLOSE: 'app:close',
  APP_SHOW_WINDOW: 'app:showWindow',
  APP_HIDE_WINDOW: 'app:hideWindow',
  APP_OPEN_EXTERNAL: 'app:openExternal',

  PROMPTS_GET_ALL: 'prompts:getAll',
  PROMPTS_GET_BUILTIN: 'prompts:getBuiltin',
  PROMPTS_GET_CUSTOM: 'prompts:getCustom',
  PROMPTS_GET_BY_ID: 'prompts:getById',
  PROMPTS_ADD: 'prompts:add',
  PROMPTS_UPDATE: 'prompts:update',
  PROMPTS_DELETE: 'prompts:delete',
  PROMPTS_GET_BY_TYPE: 'prompts:getByType',

  SESSION_GET_CONFIG: 'session:getConfig',
  SESSION_UPDATE_CONFIG: 'session:updateConfig',
  SESSION_GET_ALL: 'session:getAll',
  SESSION_GET_ACTIVE: 'session:getActive',
  SESSION_GET_BY_ID: 'session:getById',
  SESSION_GET_BY_ACCOUNT: 'session:getByAccount',
  SESSION_GET_BY_PROVIDER: 'session:getByProvider',
  SESSION_DELETE: 'session:delete',
  SESSION_CLEAR_ALL: 'session:clearAll',
  SESSION_CLEAN_EXPIRED: 'session:cleanExpired',

  MANAGEMENT_API_GET_CONFIG: 'managementApi:getConfig',
  MANAGEMENT_API_UPDATE_CONFIG: 'managementApi:updateConfig',
  MANAGEMENT_API_GENERATE_SECRET: 'managementApi:generateSecret',

  CONTEXT_MANAGEMENT_GET_CONFIG: 'contextManagement:getConfig',
  CONTEXT_MANAGEMENT_UPDATE_CONFIG: 'contextManagement:updateConfig',

  CHAT_SEND_MESSAGE: 'chat:sendMessage',
  CHAT_STREAM_CHUNK: 'chat:streamChunk',
  CHAT_STREAM_REASONING: 'chat:streamReasoning',
  CHAT_STREAM_TOOL_START: 'chat:streamToolStart',
  CHAT_STREAM_TOOL_RESULT: 'chat:streamToolResult',
  CHAT_STREAM_NEEDS_USER: 'chat:streamNeedsUser',
  CHAT_STREAM_ABORTED: 'chat:streamAborted',
  CHAT_STREAM_DONE: 'chat:streamDone',
  CHAT_STREAM_ERROR: 'chat:streamError',
  CHAT_GET_HISTORY: 'chat:getHistory',
  CHAT_CLEAR_HISTORY: 'chat:clearHistory',
  CHAT_GET_CONFIG: 'chat:getConfig',
  CHAT_SET_CONFIG: 'chat:setConfig',
  CHAT_EXECUTE_COMMAND: 'chat:executeCommand',

  // Profiles (配置组管理)
  PROFILES_GET_ALL: 'profiles:getAll',
  PROFILES_GET_ACTIVE: 'profiles:getActive',
  PROFILES_SET_ACTIVE: 'profiles:setActive',
  PROFILES_UPSERT: 'profiles:upsert',
  PROFILES_REMOVE: 'profiles:remove',

  // .doge config file management
  DOGE_LIST_CONFIG_FILES: 'doge:listConfigFiles',
  DOGE_READ_CONFIG_FILE: 'doge:readConfigFile',
  DOGE_DELETE_CONFIG_FILE: 'doge:deleteConfigFile',

  // Multi-agent team task
  TEAM_EXECUTE: 'team:execute',
  TEAM_STREAM_PHASE: 'team:streamPhase',
  TEAM_STREAM_DISCUSSION: 'team:streamDiscussion',
  TEAM_STREAM_TASK: 'team:streamTask',
  TEAM_STREAM_DONE: 'team:streamDone',
  TEAM_STREAM_ERROR: 'team:streamError',
  TEAM_GET_RESULT: 'team:getResult',

  // ==================== Config Groups ====================
  CONFIG_GROUPS_LIST: 'configGroups:list',
  CONFIG_GROUPS_GET: 'configGroups:get',
  CONFIG_GROUPS_GET_BY_ID: 'configGroups:getById',
  CONFIG_GROUPS_CREATE: 'configGroups:create',
  CONFIG_GROUPS_UPDATE: 'configGroups:update',
  CONFIG_GROUPS_DELETE: 'configGroups:delete',
  CONFIG_GROUPS_SET_ACTIVE: 'configGroups:setActive',
  CONFIG_GROUPS_SWITCH: 'configGroups:switch',

  // Cookie Session Management
  COOKIE_SESSION_OPEN_LOGIN: 'cookie:session:openLogin',
  COOKIE_SESSION_GET_STATUS: 'cookie:session:getStatus',
  COOKIE_SESSION_GET_CREDENTIALS: 'cookie:session:getCredentials',
  COOKIE_SESSION_INIT: 'cookie:session:init',
  COOKIE_SESSION_DESTROY: 'cookie:session:destroy',
  COOKIE_SESSION_CLEAR_LOGIN: 'cookie:session:clearLogin',
  COOKIE_SESSION_CREDENTIALS_CHANGED: 'cookie:session:credentialsChanged',

  // Log category config
  LOG_GET_CATEGORY_CONFIG: 'log:getCategoryConfig',
  LOG_UPDATE_CATEGORY_CONFIG: 'log:updateCategoryConfig',

  // ==================== Plans Management ====================
  PLANS_GET_ALL: 'plans:getAll',
  PLANS_GET_BY_ID: 'plans:getById',
  PLANS_CREATE: 'plans:create',
  PLANS_UPDATE: 'plans:update',
  PLANS_DELETE: 'plans:delete',
  PLANS_EXECUTE: 'plans:execute',
  PLANS_STREAM_PHASE: 'plans:streamPhase',
  PLANS_STREAM_DONE: 'plans:streamDone',
  PLANS_STREAM_ERROR: 'plans:streamError',

  // ==================== Tasks Management ====================
  TASKS_GET_ALL: 'tasks:getAll',
  TASKS_GET_BY_ID: 'tasks:getById',
  TASKS_CREATE: 'tasks:create',
  TASKS_UPDATE: 'tasks:update',
  TASKS_DELETE: 'tasks:delete',
  TASKS_SET_STATUS: 'tasks:setStatus',

  // ==================== Git Management ====================
  GIT_GET_STATUS: 'git:getStatus',
  GIT_CLONE: 'git:clone',
  GIT_PULL: 'git:pull',
  GIT_PUSH: 'git:push',
  GIT_GET_LOG: 'git:getLog',
  GIT_GET_BRANCHES: 'git:getBranches',
  GIT_CHECKOUT: 'git:checkout',

  // ==================== Agent Management ====================
  AGENTS_GET_ALL: 'agents:getAll',
  AGENTS_GET_BY_ID: 'agents:getById',
  AGENTS_CREATE: 'agents:create',
  AGENTS_UPDATE: 'agents:update',
  AGENTS_DELETE: 'agents:delete',
  AGENTS_EXECUTE: 'agents:execute',
  AGENTS_STREAM_OUTPUT: 'agents:streamOutput',
  AGENTS_STREAM_DONE: 'agents:streamDone',
  AGENTS_STREAM_ERROR: 'agents:streamError',

  // ==================== Commands Management ====================
  COMMANDS_GET_ALL: 'commands:getAll',
  COMMANDS_GET_BUILTIN: 'commands:getBuiltin',
  COMMANDS_GET_CUSTOM: 'commands:getCustom',
  COMMANDS_ADD: 'commands:add',
  COMMANDS_UPDATE: 'commands:update',
  COMMANDS_DELETE: 'commands:delete',
  COMMANDS_EXECUTE: 'commands:execute',

  // ==================== Workflows Management ====================
  WORKFLOWS_GET_ALL: 'workflows:getAll',
  WORKFLOWS_GET_BY_ID: 'workflows:getById',
  WORKFLOWS_CREATE: 'workflows:create',
  WORKFLOWS_UPDATE: 'workflows:update',
  WORKFLOWS_DELETE: 'workflows:delete',
  WORKFLOWS_EXECUTE: 'workflows:execute',
  WORKFLOWS_STREAM_STEP: 'workflows:streamStep',
  WORKFLOWS_STREAM_DONE: 'workflows:streamDone',
  WORKFLOWS_STREAM_ERROR: 'workflows:streamError',

  // ==================== MCP Management ====================
  MCP_GET_CONFIG: 'mcp:getConfig',
  MCP_UPDATE_CONFIG: 'mcp:updateConfig',
  MCP_GET_SERVERS: 'mcp:getServers',
  MCP_GET_SERVER_BY_ID: 'mcp:getServerById',
  MCP_ADD_SERVER: 'mcp:addServer',
  MCP_REMOVE_SERVER: 'mcp:removeServer',
  MCP_TEST_CONNECTION: 'mcp:testConnection',
  MCP_GET_TOOLS: 'mcp:getTools',

  // ==================== Plugins Management ====================
  PLUGINS_GET_ALL: 'plugins:getAll',
  PLUGINS_GET_BUILTIN: 'plugins:getBuiltin',
  PLUGINS_GET_INSTALLED: 'plugins:getInstalled',
  PLUGINS_ADD: 'plugins:add',
  PLUGINS_INSTALL: 'plugins:install',
  PLUGINS_UNINSTALL: 'plugins:uninstall',
  PLUGINS_ENABLE: 'plugins:enable',
  PLUGINS_DISABLE: 'plugins:disable',
  PLUGINS_UPDATE: 'plugins:update',
  PLUGINS_GET_BY_ID: 'plugins:getById',
  PLUGINS_GET_ENABLED_LIST: 'plugins:getEnabledList',
  PLUGINS_SET_ENABLED_LIST: 'plugins:setEnabledList',

  // ==================== Other Config ====================
  OTHER_CONFIG_GET: 'otherConfig:get',
  OTHER_CONFIG_UPDATE: 'otherConfig:update',
  OTHER_CONFIG_GET_ADVANCED: 'otherConfig:getAdvanced',
  OTHER_CONFIG_UPDATE_ADVANCED: 'otherConfig:updateAdvanced',
  OTHER_CONFIG_RESET: 'otherConfig:reset',

  // ==================== Tool Management ====================
  TOOLS_GET_ALL: 'tools:getAll',
  TOOLS_GET_GROUPS: 'tools:getGroups',
  TOOLS_GET_HINT_RULES: 'tools:getHintRules',
  TOOLS_ADD: 'tools:add',
  TOOLS_UPDATE: 'tools:update',
  TOOLS_REMOVE: 'tools:remove',
  TOOLS_TOGGLE: 'tools:toggle',
  TOOLS_ADD_GROUP: 'tools:addGroup',
  TOOLS_UPDATE_GROUP: 'tools:updateGroup',
  TOOLS_REMOVE_GROUP: 'tools:removeGroup',
  TOOLS_ADD_TO_GROUP: 'tools:addToGroup',
  TOOLS_REMOVE_FROM_GROUP: 'tools:removeFromGroup',
  TOOLS_ADD_HINT_RULE: 'tools:addHintRule',
  TOOLS_UPDATE_HINT_RULE: 'tools:updateHintRule',
  TOOLS_REMOVE_HINT_RULE: 'tools:removeHintRule',
  TOOLS_MATCH_HINTS: 'tools:matchHints',
  TOOLS_RESET: 'tools:reset',
  TOOLS_GET_BY_ID: 'tools:getById',

  // Generic management import/export
  MGMT_EXPORT: 'mgmt:export',
  MGMT_IMPORT: 'mgmt:import',
  MGMT_BACKUP: 'mgmt:backup',
  MGMT_RESTORE: 'mgmt:restore',
  MGMT_GET_ALL_BACKUPS: 'mgmt:getBackups',
  MGMT_DELETE_BACKUP: 'mgmt:deleteBackup',
} as const

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels]
