import type { ChatCompletionMessageToolCall } from '../types';
export interface ExtractedToolCall {
    id: string;
    type: 'function';
    function: {
        name: string;
        arguments: string;
    };
    rawText?: string;
    confidence: 'high' | 'medium' | 'low';
    /** True when this tool call was auto-generated by the proxy (declarative intent extraction) */
    generatedByProxy?: boolean;
}
export interface ExtractionResult {
    content: string;
    toolCalls: ExtractedToolCall[];
    protocol: string;
    rawMatches: string[];
}
export declare class ToolCallExtractor {
    private buffer;
    private seen;
    reset(): void;
    process(text: string): ExtractionResult;
    flush(): ExtractionResult;
    private findToolCallInBuffer;
}
/**
 * 从非流式文本中提取工具调用
 */
export declare function extractToolCallsFromText(text: string): ExtractionResult;
/**
 * 转换为 OpenAI 格式的工具调用
 */
export declare function toOpenAIToolCall(tc: ExtractedToolCall): ChatCompletionMessageToolCall;
