import type { ChatCompletionMessageToolCall } from '../types';
import { normalizeToolName, readBalancedJson, stableStringify, looksLikeToolCall, mapCommandForPlatform } from './protocols/shared.ts';

// ─── 公共类型 ──────────────────────────────────────────
export interface ExtractedToolCall {
  id: string;
  type: 'function';
  function: {
    name: string;
    arguments: string;
  };
  rawText?: string;
  confidence: 'high' | 'medium' | 'low';
  /** True when this tool call was auto-generated by the proxy (declarative intent extraction) */
  generatedByProxy?: boolean;
}

export interface ExtractionResult {
  content: string;
  toolCalls: ExtractedToolCall[];
  protocol: string;
  rawMatches: string[];
}

// ─── 内部工具函数 ──────────────────────────────────────
// TOOL_NAME_MAPPING, normalizeToolName, readBalancedJson, mapCommandForPlatform → ../protocols/shared.ts

/** 生成随机 ID（7位） */
function generateId(): string {
  return Math.random().toString(36).slice(2, 9);
}

/** 根据参数结构推测工具名 */
function inferToolNameFromArgs(args: Record<string, unknown>): string | null {
  if (args.command !== undefined || args.cmd !== undefined) return 'Bash';
  if (args.code !== undefined) return 'CodeInterpreter';
  if (args.queries !== undefined || args.query !== undefined) return 'WebSearch';
  if (args.url !== undefined || args.urls !== undefined) return 'WebExtractor';
  if (args.file_path !== undefined || args.filePath !== undefined) return 'Read';
  if (args.pattern !== undefined) {
    if (args.path === undefined || args.path === '' || args.recursive === true) return 'Glob';
    return 'Grep';
  }
  if (args.directory !== undefined || args.dir !== undefined) return 'ListFiles';
  if ((args.old_string !== undefined || args.new_string !== undefined) && args.path) return 'StrReplaceEditor';
  return null;
}

/** 尝试解析 JSON（含 Markdown 代码块清理 + 5 层容错 fallback） */
function tryParseJSON(str: string): unknown | null {
  let cleaned = str.trim();
  if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```(?:json)?\s*/, '').replace(/\s*```$/, '');
  }
  try { return JSON.parse(cleaned); } catch { /* continue to fallbacks */ }

  // Attempt 1: 转义字符串内未转义换行符和制表符
  try {
    let inString = false, isEscaped = false, fixedStr = '';
    for (let i = 0; i < cleaned.length; i++) {
      const ch = cleaned[i];
      if (ch === '\\' && !isEscaped) { isEscaped = true; fixedStr += ch; }
      else if (ch === '"' && !isEscaped) { inString = !inString; fixedStr += ch; }
      else if (inString && (ch === '\n' || ch === '\r' || ch === '\t')) {
        if (ch === '\n') fixedStr += '\\n';
        else if (ch === '\r') fixedStr += '\\r';
        else if (ch === '\t') fixedStr += '\\t';
      } else { isEscaped = false; fixedStr += ch; }
    }
    return JSON.parse(fixedStr);
  } catch { /* continue */ }

  // Attempt 2: 移除外层 JSON token 间的空白字符（保留字符串内部）
  try {
    let inString = false, isEscaped = false, compactStr = '';
    for (let i = 0; i < cleaned.length; i++) {
      const ch = cleaned[i];
      if (ch === '\\' && !isEscaped) { isEscaped = true; compactStr += ch; }
      else if (ch === '"' && !isEscaped) { inString = !inString; compactStr += ch; }
      else if (!inString && (ch === '\n' || ch === '\r' || ch === '\t')) { continue; }
      else { isEscaped = false; compactStr += ch; }
    }
    return JSON.parse(compactStr);
  } catch { /* continue */ }

  // Attempt 3: 自动补全缺失的 key 引号（如 {filePath: "x"} → {"filePath": "x"}）
  try {
    const quoted = cleaned.replace(/([{,]\s*)([a-zA-Z_][a-zA-Z0-9_]*)\s*:/g, '$1"$2":');
    let inString = false, isEscaped = false, compactStr = '';
    for (let i = 0; i < quoted.length; i++) {
      const ch = quoted[i];
      if (ch === '\\' && !isEscaped) { isEscaped = true; compactStr += ch; }
      else if (ch === '"' && !isEscaped) { inString = !inString; compactStr += ch; }
      else if (!inString && (ch === '\n' || ch === '\r')) { continue; }
      else { isEscaped = false; compactStr += ch; }
    }
    return JSON.parse(compactStr);
  } catch { /* continue */ }

  // Attempt 4: 单引号转双引号（兼容 Python dict 风格）
  try {
    const doubleQuoted = cleaned.replace(/'/g, '"');
    return JSON.parse(doubleQuoted);
  } catch { /* all attempts failed */ }

  return null;
}

/** Regex 兜底：针对 write_to_file / replace_in_file 等已知工具的严重破损 JSON */
function tryRegexFallback(str: string): any | null {
  try {
    if (str.includes('"filePath"') && str.includes('"content"')) {
      const filePathMatch = str.match(/"filePath"\s*:\s*"([^"]+)"/);
      if (filePathMatch) {
        const contentStart = str.indexOf('"content"');
        if (contentStart !== -1) {
          const valueStart = str.indexOf('"', contentStart + 9) + 1;
          const endMatch = str.match(/"\s*\}\s*(?:\[\/call\])?\s*$/);
          if (endMatch && valueStart > 0 && endMatch.index! > valueStart) {
            const contentValue = str.substring(valueStart, endMatch.index!);
            return { filePath: filePathMatch[1], content: contentValue.replace(/\\n/g, '\n').replace(/\\"/g, '"') };
          }
        }
      }
    }
    if (str.includes('"filePath"') && str.includes('"old_str"') && str.includes('"new_str"')) {
      const filePathMatch = str.match(/"filePath"\s*:\s*"([^"]+)"/);
      if (filePathMatch) {
        const oldStrStart = str.indexOf('"old_str"');
        const newStrStart = str.indexOf('"new_str"');
        if (oldStrStart !== -1 && newStrStart !== -1) {
          const oldStrValueStart = str.indexOf('"', oldStrStart + 9) + 1;
          const oldStrValueEnd = str.lastIndexOf('"', newStrStart - 1);
          const newStrValueStart = str.indexOf('"', newStrStart + 9) + 1;
          const endMatch = str.match(/"\s*\}\s*(?:\[\/call\])?\s*$/);
          if (endMatch && oldStrValueStart > 0 && endMatch.index! > oldStrValueStart && newStrValueStart > 0 && endMatch.index! > newStrValueStart) {
            const oldStrValue = str.substring(oldStrValueStart, oldStrValueEnd);
            const newStrValue = str.substring(newStrValueStart, endMatch.index!);
            return {
              filePath: filePathMatch[1],
              old_str: oldStrValue.replace(/\\n/g, '\n').replace(/\\"/g, '"'),
              new_str: newStrValue.replace(/\\n/g, '\n').replace(/\\"/g, '"'),
            };
          }
        }
      }
    }
  } catch { /* regex fallback failed */ }
  return null;
}

/** 检测反引号代码块 */
function detectBacktickCodeBlock(text: string): { start: number; end: number; language: string; content: string } | null {
  let i = 0;
  while (i < text.length) {
    if (text[i] === '`') {
      let start = i, cnt = 0;
      while (i < text.length && text[i] === '`') { cnt++; i++; }
      if (cnt >= 3) {
        let langStart = i;
        while (langStart < text.length && /\s/.test(text[langStart])) langStart++;
        let langEnd = langStart;
        while (langEnd < text.length && /[a-zA-Z0-9_-]/.test(text[langEnd])) langEnd++;
        const language = langEnd > langStart ? text.slice(langStart, langEnd).toLowerCase() : '';
        let contentStart = langEnd;
        while (contentStart < text.length && /\s/.test(text[contentStart])) contentStart++;
        if (contentStart >= text.length) return null;
        let j = contentStart, endBacktick = -1;
        while (j < text.length) {
          if (text[j] === '`') {
            let c = 0, bt = j;
            while (j < text.length && text[j] === '`') { c++; j++; }
            if (c >= 3) { endBacktick = bt; break; }
          } else { j++; }
        }
        if (endBacktick === -1) return null;
        const content = text.slice(contentStart, endBacktick).trimEnd();
        return { start, end: endBacktick + 3, language, content };
      }
    } else { i++; }
  }
  return null;
}

/** 创建标准化 ExtractedToolCall */
function makeToolCall(
  name: string,
  args: unknown,
  confidence: 'high' | 'medium' | 'low' = 'medium'
): Omit<ExtractedToolCall, 'rawText'> {
  const normalizedName = normalizeToolName(name);
  let finalArgs: unknown = args;

  // Bash 平台映射
  if (normalizedName === 'Bash' && typeof finalArgs === 'object' && finalArgs !== null) {
    const cmd = (finalArgs as Record<string, unknown>).command ?? (finalArgs as Record<string, unknown>).cmd;
    if (cmd !== undefined) {
      finalArgs = { ...(finalArgs as object), command: mapCommandForPlatform(String(cmd)) };
    }
  }

  return {
    id: `call_${generateId()}_${Date.now()}`,
    type: 'function',
    function: {
      name: normalizedName,
      arguments: typeof finalArgs === 'string' ? finalArgs : JSON.stringify(finalArgs ?? {}),
    },
    confidence,
  };
}

// ─── 核心提取器 ──────────────────────────────────────────
export class ToolCallExtractor {
  private buffer = '';
  private seen = new Set<string>();

  reset(): void {
    this.buffer = '';
    this.seen.clear();
  }

  process(text: string): ExtractionResult {
    this.buffer += text;
    const toolCalls: ExtractedToolCall[] = [];
    const rawMatches: string[] = [];

    // 循环提取所有完整的工具调用
    while (true) {
      const result = this.findToolCallInBuffer();
      if (!result) break;

      const { name, args, confidence, rawText, end, generatedByProxy } = result;

      // 构造唯一键去重（stableStringify 保证对象 key 顺序不影响去重结果）
      const key = `${name}:${stableStringify(args)}`
      if (this.seen.has(key)) {
        this.buffer = this.buffer.slice(end);
        continue;
      }
      this.seen.add(key);

      // 创建工具调用对象
      const tc = makeToolCall(name, args, confidence);
      const fullTc: ExtractedToolCall = { ...tc, rawText, generatedByProxy };

      toolCalls.push(fullTc);
      rawMatches.push(rawText);

      this.buffer = this.buffer.slice(end);
    }

    // 按置信度排序
    toolCalls.sort((a, b) => {
      const order = { high: 0, medium: 1, low: 2 };
      return order[a.confidence] - order[b.confidence];
    });

    // Fallback: scan remaining buffer for all balanced JSON objects that look like tool calls
    if (toolCalls.length === 0) {
      const jsonCalls = scanAllBalancedJson(this.buffer)
      for (const call of jsonCalls) {
        const key = `${call.name}:${stableStringify(call.args)}`
        if (!this.seen.has(key)) {
          this.seen.add(key)
          const tc = makeToolCall(call.name, call.args, 'medium')
          toolCalls.push({ ...tc, rawText: call.rawText })
          rawMatches.push(call.rawText)
        }
      }
      // Remove scanned portions from buffer
      if (jsonCalls.length > 0) {
        const lastEnd = jsonCalls[jsonCalls.length - 1].end
        this.buffer = this.buffer.slice(lastEnd)
      }
    }

    return {
      content: this.buffer,
      toolCalls,
      protocol: toolCalls.length > 0 ? 'extracted' : 'unknown',
      rawMatches,
    };
  }

  flush(): ExtractionResult {
    const content = this.buffer;
    this.buffer = '';
    return { content, toolCalls: [], protocol: 'unknown', rawMatches: [] };
  }

  // ─── 查找单个工具调用（返回原始信息） ────────────────
  private findToolCallInBuffer(): {
    name: string;
    args: unknown;
    confidence: 'high' | 'medium' | 'low';
    rawText: string;
    end: number;
    generatedByProxy?: boolean;
  } | null {
    const text = this.buffer;

    // 0. 声明式意图：模型说"我来列出/读取/运行 xxx" → 自动转为工具调用
    const intentResult = detectDeclarativeIntent(text)
    if (intentResult) return intentResult

    // 1. {"name": "ToolName", "arguments": {...}} 或 "arguments": "..."
    const standardNamePattern = /\{\s*"name"\s*:\s*"([^"]+)"\s*,\s*"arguments"\s*:\s*("[^"]*"|\{[\s\S]*?\})\s*\}/i;
    let match = standardNamePattern.exec(text);
    if (match) {
      const argsStr = match[2];
      const parsedArgs = tryParseJSON(argsStr);
      return { name: match[1], args: parsedArgs ?? argsStr, confidence: 'high', rawText: match[0], end: match.index + match[0].length };
    }

    // 2. 平衡 JSON 含 name 字段
    const jsonNameStart = /\{\s*"name"\s*:\s*"/i.exec(text);
    if (jsonNameStart) {
      const balanced = readBalancedJson(text, jsonNameStart.index);
      if (balanced) {
        const parsed = tryParseJSON(balanced.json);
        if (parsed && typeof parsed === 'object' && parsed !== null) {
          const p = parsed as Record<string, unknown>;
          if (typeof p.name === 'string') {
            const args = p.arguments !== undefined ? p.arguments : p;
            return { name: p.name, args, confidence: 'high', rawText: balanced.json, end: balanced.end };
          }
        }
      }
    }

    // 3. {"tool": "ToolName", "arguments": ...}
    const toolFieldPattern = /\{\s*"tool"\s*:\s*"([^"]+)"\s*,\s*"arguments"\s*:\s*(\{[^}]*\}|"[^"]*")\s*\}/i;
    match = toolFieldPattern.exec(text);
    if (match) {
      const argsStr = match[2];
      const parsedArgs = tryParseJSON(argsStr);
      return { name: match[1], args: parsedArgs ?? argsStr, confidence: 'high', rawText: match[0], end: match.index + match[0].length };
    }

    // 4. <|im_start|>assistant<|im_start|>tool_call... 格式
    const imStartPattern = /<\|im_start\|>assistant\s*<\|im_start\|>tool_call\s*([\s\S]*?)<\|im_start\|>/i;
    match = imStartPattern.exec(text);
    if (match) {
      const inner = match[1].trim();
      let name = 'unknown', args: unknown = {};
      const parsed = tryParseJSON(inner);
      if (parsed && typeof parsed === 'object' && parsed !== null) {
        const p = parsed as Record<string, unknown>;
        name = typeof p.name === 'string' ? p.name : name;
        args = p.arguments !== undefined ? p.arguments : p;
      } else {
        const nameTag = /<name>([^<]+)<\/name>/i.exec(inner);
        const argsTag = /<arguments>([\s\S]*?)<\/arguments>/i.exec(inner);
        if (nameTag) name = nameTag[1].trim();
        if (argsTag) {
          const parsedArgs = tryParseJSON(argsTag[1]);
          args = parsedArgs ?? argsTag[1].trim();
        } else {
          args = inner;
        }
      }
      return { name, args, confidence: 'high', rawText: match[0], end: match.index + match[0].length };
    }

    // 5. 反引号代码块（bash/cmd/sh/powershell...）
    const backtick = detectBacktickCodeBlock(text);
    if (backtick && ['bash', 'cmd', 'shell', 'sh', 'powershell', 'batch', 'ps1'].includes(backtick.language)) {
      const command = backtick.content.trim();
      if (command) {
        return {
          name: 'bash',
          args: { command },
          confidence: 'high',
          rawText: text.slice(backtick.start, backtick.end),
          end: backtick.end,
        };
      }
    }

    // 6. <bash><command>...</command></bash>
    const bashXml = /<bash>\s*<command>([\s\S]*?)<\/command>\s*<\/bash>/i.exec(text);
    if (bashXml) {
      const command = bashXml[1].trim();
      if (command) {
        return {
          name: 'bash',
          args: { command },
          confidence: 'high',
          rawText: bashXml[0],
          end: bashXml.index + bashXml[0].length,
        };
      }
    }

    // 7. <tool_call name="ToolName">...</tool_call> （带属性）
    const toolCallAttr = /<tool_call\s+name\s*=\s*["']([^"']+)["']\s*>([\s\S]*?)<\/tool_call>/i.exec(text);
    if (toolCallAttr) {
      const name = toolCallAttr[1];
      const inner = toolCallAttr[2].trim();
      let args: unknown;
      const parsed = tryParseJSON(inner);
      if (parsed && typeof parsed === 'object' && parsed !== null) {
        args = parsed;
      } else {
        // 尝试提取子标签参数
        const params: Record<string, string> = {};
        const paramRegex = /<([a-zA-Z0-9_]+)>([\s\S]*?)<\/\1>/gi;
        let pm;
        while ((pm = paramRegex.exec(inner)) !== null) {
          params[pm[1]] = pm[2].trim();
        }
        args = Object.keys(params).length > 0 ? params : inner;
      }
      return { name, args, confidence: 'high', rawText: toolCallAttr[0], end: toolCallAttr.index + toolCallAttr[0].length };
    }

    // 8. <tool_call><name>...</name><arguments>...</arguments></tool_call>
    const toolCallNested = /<tool_call>\s*<name>([^<]+)<\/name>\s*<arguments>([\s\S]*?)<\/arguments>\s*<\/tool_call>/i.exec(text);
    if (toolCallNested) {
      const name = toolCallNested[1].trim();
      const argsStr = toolCallNested[2].trim();
      const parsedArgs = tryParseJSON(argsStr);
      return { name, args: parsedArgs ?? argsStr, confidence: 'high', rawText: toolCallNested[0], end: toolCallNested.index + toolCallNested[0].length };
    }

    // 9. <function_calls> 包裹的调用
    const fcTag = /<function_calls>([\s\S]*?)<\/function_calls>/i.exec(text);
    if (fcTag) {
      const inner = fcTag[1];
      // XML 风格
      const fcItem = /<function_call\s+name\s*=\s*["']([^"']+)["']\s*>([\s\S]*?)<\/function_call>/i.exec(inner);
      if (fcItem) {
        const name = fcItem[1];
        const fcInner = fcItem[2];
        const params: Record<string, unknown> = {};
        const paramRegex = /<parameter\s+name\s*=\s*["']([^"']+)["']\s*>([\s\S]*?)<\/parameter>/gi;
        let pm;
        while ((pm = paramRegex.exec(fcInner)) !== null) {
          let val: unknown = pm[2].trim();
          if (val === 'true') val = true;
          else if (val === 'false') val = false;
          else if (!isNaN(Number(val))) val = Number(val);
          params[pm[1]] = val;
        }
        const args = Object.keys(params).length > 0 ? params : fcInner.trim();
        return { name, args, confidence: 'high', rawText: fcTag[0], end: fcTag.index + fcTag[0].length };
      }
      // JSON 风格
      const parsed = tryParseJSON(inner.trim());
      if (parsed && typeof parsed === 'object' && parsed !== null) {
        const candidate = Array.isArray(parsed) ? (parsed as unknown[])[0] : parsed;
        const p = candidate as Record<string, unknown>;
        if (candidate && typeof candidate === 'object') {
          const name = p.name || p.tool || inferToolNameFromArgs(p) || 'unknown';
          const args = p.arguments ?? p.parameters ?? p;
          return { name, args, confidence: 'medium', rawText: fcTag[0], end: fcTag.index + fcTag[0].length };
        }
      }
    }

    // 10. <tool>...</tool> (JSON inside)
    const toolTag = /<tool>([\s\S]*?)<\/tool>/i.exec(text);
    if (toolTag) {
      const parsed = tryParseJSON(toolTag[1].trim());
      if (parsed && typeof parsed === 'object' && parsed !== null) {
        const p = parsed as Record<string, unknown>;
        const name = p.name || p.tool || inferToolNameFromArgs(p) || 'unknown';
        const args = p.arguments ?? p.parameters ?? p;
        return { name, args, confidence: 'high', rawText: toolTag[0], end: toolTag.index + toolTag[0].length };
      }
    }

    // 11. <tool_calling><name>...</name><arguments>...</arguments></tool_calling>
    const toolCallingTag = /<tool_calling>([\s\S]*?)<\/tool_calling>/i.exec(text);
    if (toolCallingTag) {
      const inner = toolCallingTag[1];
      const nameMatch = /<name>([^<]+)<\/name>/i.exec(inner);
      const argsMatch = /<arguments>([\s\S]*?)<\/arguments>/i.exec(inner);
      if (nameMatch && argsMatch) {
        const name = nameMatch[1].trim();
        const argsStr = argsMatch[1].trim();
        const parsedArgs = tryParseJSON(argsStr);
        return { name, args: parsedArgs ?? { raw: argsStr }, confidence: 'high', rawText: toolCallingTag[0], end: toolCallingTag.index + toolCallingTag[0].length };
      }
    }

    // 12. 纯 JSON 对象推断
    const bareJsonStart = /\{\s*"/.exec(text);
    if (bareJsonStart) {
      const balanced = readBalancedJson(text, bareJsonStart.index);
      if (balanced) {
        const parsed = tryParseJSON(balanced.json);
        if (parsed && typeof parsed === 'object' && parsed !== null) {
          const p = parsed as Record<string, unknown>;
          const name = inferToolNameFromArgs(p);
          if (name) {
            return { name, args: p, confidence: 'medium', rawText: balanced.json, end: balanced.end };
          }
        }
      }
    }

    // 13. Tool: Name\nArguments: {...}
    const toolArgsPattern = /\bTool:\s*([a-zA-Z0-9_:]+)\s*\nArguments:\s*/i.exec(text);
    if (toolArgsPattern) {
      const name = toolArgsPattern[1];
      const jsonStartIdx = toolArgsPattern.index + toolArgsPattern[0].length;
      let tail = text.slice(jsonStartIdx);
      const braceIdx = tail.indexOf('{');
      if (braceIdx !== -1) {
        tail = tail.slice(braceIdx);
        const balanced = readBalancedJson(tail, 0);
        if (balanced) {
          const parsed = tryParseJSON(balanced.json);
          if (parsed) {
            const end = jsonStartIdx + braceIdx + balanced.end;
            return { name, args: parsed, confidence: 'high', rawText: text.slice(toolArgsPattern.index, end), end };
          }
        }
      }
    }

    // 14. 中文模式：调用：工具名\n参数：{...}
    const cnPattern = /调用：\s*([a-zA-Z0-9_:]+)\s*\n\s*参数：\s*/i.exec(text);
    if (cnPattern) {
      const name = cnPattern[1];
      const argsStart = cnPattern.index + cnPattern[0].length;
      const balanced = readBalancedJson(text, argsStart);
      if (balanced) {
        const parsed = tryParseJSON(balanced.json);
        if (parsed) {
          return { name, args: parsed, confidence: 'high', rawText: text.slice(cnPattern.index, balanced.end), end: balanced.end };
        }
      }
    }

    // 15. Calling: ToolName {...}
    const callingPattern = /(?:^|[\s\u25CF\u276F\-*])\bCalling:\s*(\w+)\s+/i.exec(text);
    if (callingPattern) {
      const jsonStart = callingPattern.index + callingPattern[0].length;
      const balanced = readBalancedJson(text, jsonStart);
      if (balanced) {
        const raw = tryParseJSON(balanced.json);
        if (raw && typeof raw === 'object') {
          let args: unknown = raw;
          // 针对已知工具做一些归一化
          switch (callingPattern[1].toLowerCase()) {
            case 'bash':
              args = { command: String((raw as Record<string, unknown>).command ?? (raw as Record<string, unknown>).cmd ?? '') };
              break;
            case 'web_search':
              args = { queries: Array.isArray((raw as Record<string, unknown>).queries) ? (raw as Record<string, unknown>).queries.map(String) : (raw as Record<string, unknown>).query ? [String((raw as Record<string, unknown>).query)] : [] };
              break;
            case 'code_interpreter':
              args = { code: String((raw as Record<string, unknown>).code ?? ''), description: String((raw as Record<string, unknown>).description ?? '') };
              break;
            case 'web_extractor':
              args = { urls: Array.isArray((raw as Record<string, unknown>).urls) ? (raw as Record<string, unknown>).urls.map(String) : [], goal: String((raw as Record<string, unknown>).goal ?? '') };
              break;
            case 'str_replace_editor':
              args = {
                command: String((raw as Record<string, unknown>).command ?? ''),
                path: String((raw as Record<string, unknown>).path ?? (raw as Record<string, unknown>).file_path ?? ''),
                old_string: String((raw as Record<string, unknown>).old_string ?? ''),
                new_string: String((raw as Record<string, unknown>).new_string ?? ''),
                ...((raw as Record<string, unknown>).view_range ? { view_range: (raw as Record<string, unknown>).view_range } : {}),
              };
              break;
          }
          return {
            name: callingPattern[1],
            args,
            confidence: 'high',
            rawText: text.slice(callingPattern.index, balanced.end),
            end: balanced.end,
          };
        }
      }
    }

    // 16. ToolName: {JSON}
    const colonJson = /^([A-Za-z][A-Za-z0-9_]*)\s*:\s*(\{[\s\S]*?\})/m.exec(text);
    if (colonJson) {
      const braceIdx = text.indexOf('{', colonJson.index + colonJson[1].length);
      if (braceIdx !== -1) {
        const balanced = readBalancedJson(text, braceIdx);
        if (balanced) {
          const parsed = tryParseJSON(balanced.json);
          if (parsed) {
            return { name: colonJson[1], args: parsed, confidence: 'medium', rawText: text.slice(colonJson.index, balanced.end), end: balanced.end };
          }
        }
      }
    }

    // 17. <tool_call>...</tool_call>（无属性，内部可以是XML或JSON）
    const genericToolCall = /<tool_call>([\s\S]*?)<\/tool_call>/i.exec(text);
    if (genericToolCall) {
      const inner = genericToolCall[1];
      // 尝试 JSON
      const parsed = tryParseJSON(inner.trim());
      if (parsed && typeof parsed === 'object' && parsed !== null) {
        const p = parsed as Record<string, unknown>;
        const name = p.name || p.tool || 'unknown';
        const args = p.arguments ?? p.parameters ?? p;
        return { name, args, confidence: 'high', rawText: genericToolCall[0], end: genericToolCall.index + genericToolCall[0].length };
      } else {
        // 尝试 XML 嵌套
        const nameMatch = /<([a-zA-Z0-9_]+)>/.exec(inner);
        if (nameMatch) {
          const tagName = nameMatch[1];
          const closeTag = `</${tagName}>`;
          const closeIdx = inner.indexOf(closeTag);
          if (closeIdx !== -1) {
            const argsXml = inner.slice(nameMatch.index + nameMatch[0].length, closeIdx);
            const params: Record<string, string> = {};
            const paramRegex = /<([a-zA-Z0-9_]+)>([\s\S]*?)<\/\1>/g;
            let pm;
            while ((pm = paramRegex.exec(argsXml)) !== null) {
              params[pm[1]] = pm[2].trim();
            }
            const args = Object.keys(params).length > 0 ? params : argsXml.trim();
            return { name: tagName, args, confidence: 'high', rawText: genericToolCall[0], end: genericToolCall.index + genericToolCall[0].length };
          }
        }
      }
    }

    // 18. Glob({...}), Bash({...}) 函数调用式
    const fnCall = /\b(Glob|Bash|Read|Grep|Write|Edit|ListFiles|CodeInterpreter|WebExtractor)\s*\(/i.exec(text);
    if (fnCall) {
      const jsonStart = fnCall.index + fnCall[0].length;
      const balanced = readBalancedJson(text, jsonStart);
      if (balanced) {
        const afterJson = text.slice(balanced.end);
        if (/^\s*\)/.test(afterJson)) {
          const parsed = tryParseJSON(balanced.json);
          if (parsed) {
            const end = balanced.end + afterJson.match(/^\s*\)/)![0].length;
            return { name: fnCall[1], args: parsed, confidence: 'high', rawText: text.slice(fnCall.index, end), end };
          }
        }
      }
    }

    // 19. ```json ... ``` 代码块
    const jsonCodeBlock = /```(?:json)?\s*\n\s*([\[{][\s\S]*?[\]}])\s*\n```/i.exec(text);
    if (jsonCodeBlock) {
      const parsed = tryParseJSON(jsonCodeBlock[1].trim());
      if (parsed) {
        const candidate = Array.isArray(parsed) ? parsed[0] : parsed;
        if (candidate && typeof candidate === 'object') {
          const name = candidate.name || candidate.tool || inferToolNameFromArgs(candidate as any) || 'unknown';
          const args = candidate.arguments ?? candidate.parameters ?? candidate;
          return { name, args, confidence: 'medium', rawText: jsonCodeBlock[0], end: jsonCodeBlock.index + jsonCodeBlock[0].length };
        }
      }
    }

    // 20. OpenAI 原生 tool_calls JSON
    const openAiToolCalls = /"tool_calls"\s*:\s*\[\s*\{\s*"id"\s*:\s*"[^"]+"\s*,\s*"type"\s*:\s*"function"\s*,\s*"function"\s*:\s*\{\s*"name"\s*:\s*"([^"]+)"\s*,\s*"arguments"\s*:\s*"([^"]*)"\s*\}\s*\}/i.exec(text);
    if (openAiToolCalls) {
      const name = openAiToolCalls[1];
      const argsStr = openAiToolCalls[2] || '{}';
      const parsedArgs = tryParseJSON(argsStr);
      return { name, args, confidence: 'high', rawText: openAiToolCalls[0], end: openAiToolCalls.index + openAiToolCalls[0].length };
    }

    // 21. 其他命令行风格 Tool: Name (args) 和 Calling: Name (args)
    const parenStyle = /(?:Tool|Calling):\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*\(([\s\S]*?)\)/gi.exec(text);
    if (parenStyle) {
      const name = parenStyle[1];
      let argsStr = parenStyle[2].trim();
      let args: unknown;
      if (argsStr.startsWith('{') || argsStr.startsWith('[')) {
        const parsedArgs = tryParseJSON(argsStr);
        args = parsedArgs ?? argsStr;
      } else {
        args = { input: argsStr };
      }
      return { name, args, confidence: 'medium', rawText: parenStyle[0], end: parenStyle.index + parenStyle[0].length };
    }

    // 22. [tool_calls] marker format: [tool_calls]{"tool":"name","args":{...}}...
    const toolCallsMarker = text.indexOf('[tool_calls]')
    if (toolCallsMarker !== -1) {
      const contentBefore = text.substring(0, toolCallsMarker).trim()
      const toolCallsStr = text.substring(toolCallsMarker + '[tool_calls]'.length).trim()
      const parsed = tryParseJSON('[' + toolCallsStr + ']')
      if (parsed && Array.isArray(parsed) && parsed.length > 0) {
        const first = parsed[0] as Record<string, unknown>
        const name = first.tool || first.name || first.tool_name || 'unknown'
        const args = first.arguments ?? first.args ?? first.input ?? first
        return {
          name,
          args,
          confidence: 'high',
          rawText: text.slice(toolCallsMarker),
          end: text.length,
        }
      }
    }

    // 23. [Called tools: Name (args), Name2 (args2)]
    const calledToolsMatch = /\[Called tools?:\s*/i.exec(text)
    if (calledToolsMatch) {
      const innerStart = calledToolsMatch.index + calledToolsMatch[0].length
      const inner = text.slice(innerStart)
      const closeIdx = inner.indexOf(']')
      if (closeIdx !== -1) {
        const callsStr = inner.slice(0, closeIdx).trim()
        const calls = parseCalledToolsList(callsStr)
        if (calls.length > 0) {
          const first = calls[0]
          return {
            name: first.name,
            args: first.args,
            confidence: 'high',
            rawText: text.slice(calledToolsMatch.index, innerStart + closeIdx + 1),
            end: innerStart + closeIdx + 1,
          }
        }
      }
    }

    // 24. Action: Name\nArguments: {...} (non-JSON args)
    const actionMatch = /Action:\s*(\w+)/i.exec(text)
    if (actionMatch) {
      const name = actionMatch[1]
      const argsMatch = /\bArguments:\s*([\s\S]*?)(?:\n\s*\w|$)/i.exec(text.slice(actionMatch.index))
      let args: unknown = {}
      if (argsMatch) {
        const argsBody = argsMatch[1].trim()
        if (argsBody.startsWith('{')) {
          const balanced = readBalancedJson(argsBody, 0)
          if (balanced) {
            const parsed = tryParseJSON(balanced.json)
            if (parsed) args = parsed
          }
        } else if (argsBody) {
          args = { value: argsBody }
        }
      }
      return {
        name,
        args,
        confidence: 'medium',
        rawText: text.slice(actionMatch.index, actionMatch.index + actionMatch[0].length + (argsMatch?.length ?? 0)),
        end: actionMatch.index + actionMatch[0].length + (argsMatch?.length ?? 0),
      }
    }

    return null;
  }
}

/**
 * 声明式意图检测：从自然语言中提取工具调用
 * 例如："我来列出 src/" → ListFiles(directory="src/")
 *
 * 使用声明式规则引擎，每条规则独立匹配，按 priority 排序执行。
 * 新增意图模式只需在 INTENT_RULES 数组中添加一条规则。
 */
interface IntentMatch {
  name: string
  args: Record<string, unknown>
  confidence: 'medium'
  rawText: string
  end: number
  generatedByProxy?: boolean
}

interface IntentRule {
  /** 执行优先级，数字越小越先执行 */
  priority: number
  /** 规则名称，用于调试日志 */
  label: string
  /** 匹配函数，返回 IntentMatch 或 null */
  match: (text: string) => IntentMatch | null
}

// ─── 工具函数 ──────────────────────────────────────────────
function cleanIntentTarget(target: string): string {
  return target.replace(/[的]$/, '').replace(/[的|文件|内容|目录|文件夹|路径|下]$/, '').trim()
}

function looksLikePath(target: string): boolean {
  return target.length >= 2 && (
    target.includes('/') || target.includes('\\') || target.includes('.') || /^\w+\.\w+$/.test(target)
  )
}

function isListTarget(target: string): boolean {
  return /[\\/]$/.test(target) || (!/\.\w+$/.test(target) && target.includes('/'))
}

function makeIntentMatch(
  name: string,
  args: Record<string, unknown>,
  rawText: string,
  end: number,
  generatedByProxy = false,
): IntentMatch {
  return { name, args, confidence: 'medium', rawText, end, generatedByProxy }
}

// ─── 规则实现函数 ──────────────────────────────────────────
const TOOL_NAME_MAP_LOOSE: Record<string, string> = {
  bash: 'Bash', read: 'Read', write: 'Write', edit: 'Edit',
  grep: 'Grep', glob: 'Glob', ls: 'ListFiles', list: 'ListFiles',
  dir: 'ListFiles', search: 'WebSearch', web: 'WebExtractor',
}

function ruleEnPrefixedIntent(text: string): IntentMatch | null {
  const pattern = /(?:i'll|let me|i need to|i'm going to|let's|i want to|i will|gonna)\s+(?:check|read|view|see|look at|examine|inspect|open)\s+(?:the\s+)?(?:file\s+)?[`'""]?([A-Za-z0-9_.\-/\\]+)[`'""]?/i
  const match = pattern.exec(text)
  if (!match) return null
  const target = match[1].trim()
  if (!looksLikePath(target)) return null
  const isList = isListTarget(target)
  return makeIntentMatch(
    isList ? 'ListFiles' : 'Read',
    isList ? { directory: target } : { file_path: target },
    match[0], match.index + match[0].length, true,
  )
}

function ruleEnBareIntent(text: string): IntentMatch | null {
  const pattern = /\b(check|read|view|see|look at|examine|inspect|open)\s+(?:the\s+)?(?:file\s+)?[`'""]?([A-Za-z0-9_.\-/\\]+)[`'""]?/i
  const match = pattern.exec(text)
  if (!match) return null
  const target = match[2].trim()
  if (!looksLikePath(target)) return null
  const isList = isListTarget(target)
  return makeIntentMatch(
    isList ? 'ListFiles' : 'Read',
    isList ? { directory: target } : { file_path: target },
    match[0], match.index + match[0].length, true,
  )
}

function ruleQuotedPath(text: string): IntentMatch | null {
  const pattern = /(?:列出|显示|查看|看看|读取|打开)\s*[`'""]([^`'""]+)[`'""]/
  const match = pattern.exec(text)
  if (!match) return null
  const path = match[1].trim()
  if (path.length < 1) return null
  const isList = /^(列出|显示|查看|看看|ls|dir|list)/.test(text.slice(0, 10))
  return makeIntentMatch(
    isList ? 'ListFiles' : 'Read',
    isList ? { directory: path } : { file_path: path },
    match[0], match.index + match[0].length,
  )
}

function ruleAbsPath(text: string): IntentMatch | null {
  const pattern = /(?:列出|显示|查看|看看|读取|打开)\s+([a-zA-Z]:\\[^\s]+)/
  const match = pattern.exec(text)
  if (!match) return null
  const path = match[1].trim()
  const isList = /^(列出|显示|查看|看看)/.test(text)
  return makeIntentMatch(
    isList ? 'ListFiles' : 'Read',
    isList ? { directory: path } : { file_path: path },
    match[0], match.index + match[0].length,
  )
}

function ruleCnListWithPrefix(text: string): IntentMatch | null {
  const pattern = /(?:我来|让我|我要|帮你)\s*(?:列出|显示|查看|看看|ls|dir|list)\s*(?:目录|文件夹|路径|一下)?\s*[`'""]?((?:[.A-Za-z]:)?[A-Za-z0-9_.\-/\\]+)[`'""]?\s*(?:目录\s*的?\s*内容|的?内容|目录|文件夹|路径|下|里|[。.])?/
  const match = pattern.exec(text)
  if (!match) return null
  const target = match[1].replace(/[`'""]/g, '').trim()
  if (target.length < 1) return null
  return makeIntentMatch('ListFiles', { directory: target }, match[0], match.index + match[0].length)
}

function ruleCnReadWithPrefix(text: string): IntentMatch | null {
  const pattern = /(?:我来|让我|我要|帮你)?\s*(?:读取|查看|打开|读一下|看看)\s*(?:文件)?\s*[`'""]?([A-Za-z0-9_.\-/\\[\]:]+\.[A-Za-z0-9]+)[`'""]?\s*(?:的?内容|文件)?\s*[。.]?/
  const match = pattern.exec(text)
  if (!match) return null
  const target = match[1].replace(/[`'""]/g, '').trim()
  if (target.length < 1) return null
  return makeIntentMatch('Read', { file_path: target }, match[0], match.index + match[0].length)
}

function ruleCnRunWithPrefix(text: string): IntentMatch | null {
  const pattern = /(?:我来|让我|我要|帮你)?\s*(?:运行|执行|跑|执行一下)\s*(?:命令|cmd)?\s*([^\s,，。.？！?！]{1,200})/
  const match = pattern.exec(text)
  if (!match) return null
  const cmd = match[1].trim()
  if (cmd.length < 1) return null
  return makeIntentMatch('Bash', { command: cmd }, match[0], match.index + match[0].length)
}

function ruleCnList(text: string): IntentMatch | null {
  const pattern = /(?:我来|让我|我要|帮你)\s*(?:列出|显示|查看|看看)\s*(?:目录|文件夹|路径)?\s*([^\s,，。.？！?！]+?)\s*(?:目录\s*的?\s*内容|的?内容|目录|文件夹|路径|下|[。.])?/
  const match = pattern.exec(text)
  if (!match) return null
  const target = cleanIntentTarget(match[1])
  if (target.length < 1) return null
  return makeIntentMatch('ListFiles', { directory: target }, match[0], match.index + match[0].length)
}

function ruleCnRead(text: string): IntentMatch | null {
  const pattern = /(?:我来|让我|我要|帮你)\s*(?:读取|查看|打开|看看)\s*(?:文件)?\s*([^\s,，。.？！?！]+?)\s*(?:的?内容|[。.])?/
  const match = pattern.exec(text)
  if (!match) return null
  const target = cleanIntentTarget(match[1])
  if (target.length < 1) return null
  return makeIntentMatch('Read', { file_path: target }, match[0], match.index + match[0].length)
}

function ruleCnRun(text: string): IntentMatch | null {
  const pattern = /(?:我来|让我|我要|帮你)\s*(?:运行|执行|跑|执行)\s*(?:命令|cmd)?\s*([^\s,，。.？！?！]{1,100})/
  const match = pattern.exec(text)
  if (!match) return null
  const cmd = match[1].trim()
  if (cmd.length < 1) return null
  return makeIntentMatch('Bash', { command: cmd }, match[0], match.index + match[0].length)
}

function ruleSurgeTagJson(text: string): IntentMatch | null {
  const pattern = /<tool_call>\s*(\w+)\s*:\s*(\{[\s\S]*?\})/i
  const match = pattern.exec(text)
  if (!match) return null
  const name = normalizeToolName(match[1].trim())
  const parsedArgs = tryParseJSON(match[2])
  return makeIntentMatch(name, parsedArgs ?? match[2], match[0], match.index + match[0].length)
}

function ruleSurgeTagXml(text: string): IntentMatch | null {
  const pattern = /<tool_call>\s*<([a-zA-Z0-9_]+)>([\s\S]*)/i
  const match = pattern.exec(text)
  if (!match) return null
  const name = normalizeToolName(match[1].trim())
  const inner = match[2]
  const params: Record<string, string> = {}
  const paramRegex = /<([a-zA-Z0-9_]+)>([\s\S]*?)<\/\1>/gi
  let pm: RegExpExecArray | null
  while ((pm = paramRegex.exec(inner)) !== null) {
    params[pm[1]] = pm[2].trim()
  }
  const args = Object.keys(params).length > 0 ? params : inner.trim()
  return makeIntentMatch(name, args, match[0], match.index + match[0].length)
}

function ruleToolDeclareCn(text: string): IntentMatch | null {
  const pattern = /我将使用\s+(\S+?)\s+工具\s*(?:来\s*)?((?:列出|显示|查看|读取|打开|运行|执行)\s*(?:[`'""]([^`'""]+)[`'""]|[^\s。，！？]+))/
  const match = pattern.exec(text)
  if (!match) return null
  const actionWord = match[2].trim()
  const quotedPathMatch = /[`'""]([^`'""]+)[`'""]/.exec(actionWord)
  const quotedPath = quotedPathMatch ? quotedPathMatch[1].trim() : null
  const unquotedTarget = !quotedPath ? actionWord.replace(/^[^\s]+\s+/, '').trim() : null
  let name: string
  let args: Record<string, unknown> = {}
  if (/^(列出|显示|查看|ls|dir|list)/.test(actionWord)) {
    name = 'ListFiles'
    args = { directory: quotedPath || unquotedTarget || '' }
  } else if (/^(读取|打开|read|cat)/.test(actionWord)) {
    name = 'Read'
    args = { file_path: quotedPath || unquotedTarget || '' }
  } else {
    name = 'Bash'
    args = { command: (quotedPath || unquotedTarget || '').replace(/^[运行执行\s]+/, '') }
  }
  return makeIntentMatch(name, args, match[0], match.index + match[0].length)
}

function ruleLooseToolDeclare(text: string): IntentMatch | null {
  const pattern = /(?:我|我将)\s*使用\s+(\w+)\s+工具\s*(?:来\s*)?([^\s。，！？]{1,50})/i
  const match = pattern.exec(text)
  if (!match) return null
  const rawTool = match[1].trim().toLowerCase()
  const rawAction = match[2].trim()
  let name = TOOL_NAME_MAP_LOOSE[rawTool] || normalizeToolName(rawTool)
  const qp = /[`'""]([^`'""]+)[`'""]/.exec(rawAction)
  const target = qp ? qp[1].trim() : rawAction.replace(/^[运行执行\s]+/, '').trim()
  if (/^(列出|显示|ls|dir|list)/.test(rawAction) && target) {
    return makeIntentMatch('ListFiles', { directory: target }, match[0], match.index + match[0].length)
  }
  if (/^(读取|查看|read|cat)/.test(rawAction) && target) {
    return makeIntentMatch('Read', { file_path: target }, match[0], match.index + match[0].length)
  }
  if (/^(运行|执行|run)/.test(rawAction) && target) {
    return makeIntentMatch('Bash', { command: target }, match[0], match.index + match[0].length)
  }
  return null
}

// ─── 规则注册表 ──────────────────────────────────────────
const INTENT_RULES: IntentRule[] = [
  { priority: 0, label: 'enPrefixedIntent',   match: ruleEnPrefixedIntent },
  { priority: 1, label: 'enBareIntent',       match: ruleEnBareIntent },
  { priority: 2, label: 'quotedPath',         match: ruleQuotedPath },
  { priority: 3, label: 'absPath',            match: ruleAbsPath },
  { priority: 4, label: 'cnListWithPrefix',   match: ruleCnListWithPrefix },
  { priority: 5, label: 'cnReadWithPrefix',   match: ruleCnReadWithPrefix },
  { priority: 6, label: 'cnRunWithPrefix',    match: ruleCnRunWithPrefix },
  { priority: 7, label: 'cnList',             match: ruleCnList },
  { priority: 8, label: 'cnRead',             match: ruleCnRead },
  { priority: 9, label: 'cnRun',              match: ruleCnRun },
  { priority: 10, label: 'surgeTagJson',      match: ruleSurgeTagJson },
  { priority: 11, label: 'surgeTagXml',       match: ruleSurgeTagXml },
  { priority: 12, label: 'toolDeclareCn',     match: ruleToolDeclareCn },
  { priority: 13, label: 'looseToolDeclare',  match: ruleLooseToolDeclare },
]

/**
 * 从文本中按优先级检测声明式意图，返回工具调用匹配或 null。
 * 新增规则只需在 INTENT_RULES 数组中添加条目。
 */
function detectDeclarativeIntent(text: string): IntentMatch | null {
  const trimmed = text.trim()
  if (!trimmed) return null

  for (const rule of INTENT_RULES) {
    const result = rule.match(trimmed)
    if (result) return result
  }
  return null
}

/**
 * 从非流式文本中提取工具调用
 */
export function extractToolCallsFromText(text: string): ExtractionResult {
  // 如果整段文本看起来像中间工具调用 JSON（流式传输中），不提取任何内容
  // 避免把未完成的 JSON 片段泄露为文本内容
  if (looksLikeToolCall(text)) {
    return { content: '', toolCalls: [], protocol: 'unknown', rawMatches: [] }
  }

  // 清洗：剥离源码/注释行（const/let/var 声明、// 行注释、/* 块注释）。
  // 这些行里的 <tool_call> 一定是讲解/源码示例，绝不可能是真实工具。
  // 在解析前剥离，确保所有协议、所有路径的兜底提取都不会从此类行误提工具。
  const cleaned = stripSourceLikeLines(text)
  const extractor = new ToolCallExtractor();
  const result = extractor.process(cleaned);
  const flush = extractor.flush();
  return {
    content: result.content + flush.content,
    toolCalls: result.toolCalls,
    protocol: result.toolCalls.length > 0 ? result.protocol : 'unknown',
    rawMatches: result.rawMatches,
  };
}

/** 剥离"源码/注释行"：以 const/let/var（去前导空格）或 // /* 开头的行整行移除 */
function stripSourceLikeLines(text: string): string {
  return text
    .split('\n')
    .map((line) => {
      const t = line.replace(/^\s+/, '')
      if (/^(const|let|var)\s/.test(t)) return ''
      if (t.startsWith('//')) return ''
      if (t.startsWith('/*')) return ''
      return line
    })
    .join('\n')
}

/**
 * Parse "Called tools: Name1 (args1), Name2 (args2)" format
 */
function parseCalledToolsList(inner: string): Array<{ name: string; args: Record<string, unknown> }> {
  const results: Array<{ name: string; args: Record<string, unknown> }> = []
  let pos = 0

  while (pos < inner.length) {
    while (pos < inner.length && /[\s,\]]/.test(inner[pos]!)) pos++
    if (pos >= inner.length) break

    if (!/[a-zA-Z_]/.test(inner[pos]!)) break

    const nameStart = pos
    while (pos < inner.length && /\w/.test(inner[pos]!)) pos++
    const toolName = inner.substring(nameStart, pos)

    while (pos < inner.length && inner[pos] === ' ') pos++

    if (pos >= inner.length || inner[pos] !== '(') break
    pos++

    let args: Record<string, unknown> = {}
    let parsed = false

    if (pos < inner.length && inner[pos] === '{') {
      const balanced = readBalancedJson(inner, pos)
      if (balanced) {
        pos += balanced.end
        const parsedArgs = tryParseJSON(balanced.json)
        if (parsedArgs && typeof parsedArgs === 'object') {
          args = parsedArgs as Record<string, unknown>
          parsed = true
        }
      }
    }

    if (!parsed) {
      while (pos < inner.length && inner[pos] !== ')') pos++
      const rawArgs = inner.substring(argsStart, pos).trim()
      if (rawArgs) {
        const parsedArgs = tryParseJSON(rawArgs)
        if (parsedArgs && typeof parsedArgs === 'object') {
          args = parsedArgs as Record<string, unknown>
        }
      }
    }

    while (pos < inner.length && inner[pos] !== ')') pos++
    if (pos < inner.length) pos++

    results.push({ name: toolName, args })
  }

  return results
}

/**
 * Scan text for all balanced JSON objects and try to extract tool calls from each.
 * This handles cases where multiple tool calls appear as consecutive JSON objects
 * without a wrapping array or marker.
 */
function scanAllBalancedJson(text: string): Array<{ name: string; args: unknown; rawText: string; end: number }> {
  const results: Array<{ name: string; args: unknown; rawText: string; end: number }> = []
  let pos = 0

  while (pos < text.length) {
    while (pos < text.length && /\s/.test(text[pos]!)) pos++
    if (pos >= text.length) break
    if (text[pos] !== '{') break

    const balanced = readBalancedJson(text, pos)
    if (!balanced) break

    const parsed = tryParseJSON(balanced.json)
    if (parsed && typeof parsed === 'object' && parsed !== null) {
      const p = parsed as Record<string, unknown>
      const name = p.name || p.tool || p.tool_name || inferToolNameFromArgs(p)
      if (name) {
        const args = p.arguments ?? p.args ?? p.input ?? p.parameters ?? p
        results.push({
          name,
          args,
          rawText: balanced.json,
          end: pos + balanced.end,
        })
      }
    }

    pos += balanced.end
  }

  return results
}

/**
 * 转换为 OpenAI 格式的工具调用
 */
export function toOpenAIToolCall(tc: ExtractedToolCall): ChatCompletionMessageToolCall {
  return {
    id: tc.id,
    type: 'function',
    function: {
      name: tc.function.name,
      arguments: tc.function.arguments,
    },
  };
}